version: '3.8'

services:

  store_db_postgres:
    image: postgres:16.0-alpine3.18
    container_name: store_db_postgres
    environment:
      POSTGRES_USER: store_service
      POSTGRES_PASSWORD: cCdvZWt0NDk4W2llazJb
      POSTGRES_DB: store_service
    ports:
      - '5432:5432'

  store_cache:
    image: redis:7.2.4-alpine3.19
    container_name: store_cache
    ports:
      - '6379:6379'
