spring:
  application:
    name: store-service
  main:
    banner-mode: off

app:
  main:
    datasource:
      postgres-db:
        jdbc-url: jdbc:postgresql://${STORE_POSTGRES_HOST:localhost}:${STORE_POSTGRES_PORT:5432}/store_db
        username: store-service
        password: ${STORE_POSTGRES_PASSWORD:storePassWord}
        driver-class-name: org.postgresql.Driver
        connection-timeout: 20000
        minimum-idle: 5
        maximum-pool-size: 10
        max-lifetime: 90000


server:
  port: 8093


#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: WmwycXU0NG1AUmVkaXNQYXNzd29yZA==
#  cache:
#    type: redis
#    cache-names: redis-cache
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/store_service?currentSchema=store
#    username: store_service
#    password: cCdvZWt0NDk4W2llazJb
#  kafka:
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    bootstrap-servers: ${KAFKA_HOST}:9092
#