name: Build Docker Image

on:
  workflow_call:
  workflow_dispatch:

jobs:

  build_jar:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - run: tree -L 2
    
    - name: Build with Maven Wrapper
      run: ./mvnw -B package -DskipTests
  
    - run: tree -L 2

    - name: Copy artifact
      run: cp -R target/store-service**.jar application.jar
    
    - name: Extract JAR
      run: java -Djarmode=layertools -jar target/application.jar extract --destination extracted
      
    - run: tree -L 2

  #     - name: Uploading build artifacts
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: ${{ inputs.service }}-artifact
  #         path: ./${{ inputs.service }}/target/**.jar

  #     - name: Uploading Dockerfile
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: ${{ inputs.service }}-dockerfile
  #         path: ./${{ inputs.service }}/Dockerfile
  ls_java:
    runs-on: ubuntu-latest
    steps: 
    - run: java -version
  # build_and_push_images:

  #   runs-on: ubuntu-latest
  #   needs: [ build_jar ]

  #   steps:
  #     - name: Loading Build Artifact
  #       uses: actions/download-artifact@v3.0.2
  #       with:
  #         name: ${{ inputs.service }}-artifact

  #     - name: Loading Dockerfile
  #       uses: actions/download-artifact@v3.0.2
  #       with:
  #         name: ${{ inputs.service }}-dockerfile

  #     - name: DockerHub Login
  #       uses: docker/login-action@v3.0.0
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}

  #     - name: Build Docker image
  #       run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service }}

  #     - name: Push image
  #       run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service }}
